stages:
  - docker-build
  - deploy

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:bind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

deploy:
  stage: deploy
  image: node
  script:
    - echo "Testing App"
    - echo "Test successfully!"